function cost = E2ICIpalboAZD_cost(args,...                                     (1)
                                   tE2,...                                      (3)
                                   tICI500nM,...                                (4)
                                   tpalbo250nM,...                              (5)
                                   tpalbo500nM,...                              (6)
                                   tpalbo1uM,...                                (7)
                                   tpalbo750nM_13m,...                          (8)
                                   tICI750nM_13m,...                            (9)
                                   tAZD250nM_13m,...                            (10)
                                   tICI750nMAZD250nM_13m,...                    (11)
                                   tAlter_palbo750nM_ICI750nM_13m,...           (12)
                                   tAlter_palbo750nM_ICI750nMAZD250nM_13m,...   (13)
                                   simE2,...                                    (14)
                                   simICI500nM,...                              (15)
                                   simpalbo250nM,...                            (16)
                                   simpalbo500nM,...                            (17)
                                   simpalbo1uM,...                              (18)
                                   simpalbo750nM_13m,...                        (19)
                                   simICI750nM_13m,...                          (20)
                                   simAZD250nM_13m,...                          (21)
                                   simICI750nMAZD250nM_13m,...                  (22) 
                                   simAlter_palbo750nM_ICI750nM_13m,...         (23)
                                   simAlter_palbo750nM_ICI750nMAZD250nM_13m,... (24)
                                   xpalbo750nM_13m,...                          (25)
                                   xICI750nM_13m,...                            (26)
                                   xAlter_palbo750nM_ICI750nM,...               (27)
                                   xAlter_palbo750nM_ICI750nMAZD250nM_13m,...   (28)
                                   cellnum_ICI200nM_d17,...                     (29)
                                   cellnum_ICI200nM_palbo50nM_d17,...           (30)
                                   cellnum_ICI200nM_palbo100nM_d17,...          (31)
                                   cellnum_ICI200nM_palbo300nM_d17)
% Calculates the cost between model simulation and experimental data.
data = E2ICIpalboAZD_loaddata();
data = E2ICIpalboAZD_modifydata(data);
%% cost value of protein
%% CyclinE1
ind = 2;
% CyclinE1, palbo mono, w1
exp = structfun(@(x) x(ind), data.CyclinE1, 'UniformOutput',false);
[cyclinE1ratio_palbomono_w1,mse_use,val_cyclinE1ratio_palbo_w1] =...
    child_mse_p2(exp,...
                 xpalbo750nM_13m,...
                 tpalbo750nM_13m,...
                 xpalbo750nM_13m,...
                 args.ind_containcyclinE1,...
                 args);
if ~isnan(mse_use);cost = mse_error;return;end
% CyclinE1, palbo mono, w2
ind = 3;
exp = structfun(@(x) x(ind), data.CyclinE1, 'UniformOutput',false);
[cyclinE1ratio_palbomono_w2,mse_use, val_cyclinE1ratio_palbo_w2] =...
    child_mse_p2(exp,...
                 xpalbo750nM_13m,...
                 tpalbo750nM_13m,...
                 xpalbo750nM_13m,...
                 args.ind_containcyclinE1,...
                 args);
if ~isnan(mse_use);cost = mse_error;return;end
% CyclinE1, palbo mono, m12
ind = 4;
exp = structfun(@(x) x(ind), data.CyclinE1, 'UniformOutput',false);
[cyclinE1ratio_palbomono_m12,mse_use,val_cyclinE1ratio_palbo_m12] =...
    child_mse_p2(exp,...
                 xpalbo750nM_13m,...
                 tpalbo750nM_13m,...
                 xpalbo750nM_13m,...
                 args.ind_containcyclinE1,...
                 args);
if ~isnan(mse_use);cost = mse_error;return;end
% CyclinE1, alter, m12
ind = 5;
exp = structfun(@(x) x(ind), data.CyclinE1, 'UniformOutput',false);
[cyclinE1ratio_alter_m12,mse_use,val_cyclinE1ratio_alter_palbo_ICIAZD_m12] =...
    child_mse_p2(exp,...
                 xAlter_palbo750nM_ICI750nMAZD250nM_13m,...
                 tAlter_palbo750nM_ICI750nMAZD250nM_13m,...
                 xAlter_palbo750nM_ICI750nMAZD250nM_13m,...
                 args.ind_containcyclinE1,...
                 args);
if ~isnan(mse_use);cost = mse_error;return;end
%% Cdk6
%%
% Cdk6, ICI mono w1
ind = 2;
exp = structfun(@(x) x(ind), data.Cdk6, 'UniformOutput',false);
[cdk6ratio_ICImono_w1,mse_use,val_Cdk6ratio_ICI_w1] =...
    child_mse_p2(exp,...
                 xICI750nM_13m,...
                 tICI750nM_13m,...
                 xICI750nM_13m,...
                 args.ind_containcdk6,...
                 args);
if ~isnan(mse_use);cost = mse_error;return;end
% Cdk6, ICI mono w2
ind = 3;
exp = structfun(@(x) x(ind), data.Cdk6, 'UniformOutput',false);
[cdk6ratio_ICImono_w2,mse_use,val_Cdk6ratio_ICI_w2] =...
    child_mse_p2(exp,...
                 xICI750nM_13m,...
                 tICI750nM_13m,...
                 xICI750nM_13m,...
                 args.ind_containcdk6,...
                 args);
if ~isnan(mse_use);cost = mse_error;return;end
% Cdk6, ICI mono, m12
ind = 4;
exp = structfun(@(x) x(ind), data.Cdk6, 'UniformOutput',false);
[cdk6ratio_ICImono_m12,mse_use,val_Cdk6ratio_ICI_m12] =...
    child_mse_p2(exp,...
                 xICI750nM_13m,...
                 tICI750nM_13m,...
                 xICI750nM_13m,...
                 args.ind_containcdk6,...
                 args);
if ~isnan(mse_use);cost = mse_error;return;end
% Cdk6, Alter palbo ICI+AZD, m12
ind = 5;
exp = structfun(@(x) x(ind), data.Cdk6, 'UniformOutput',false);
[cdk6ratio_alter_m12,mse_use,val_Cdk6ratio_alter_palbo_ICIAZD_m12] =...
    child_mse_p2(exp,...
                 xAlter_palbo750nM_ICI750nMAZD250nM_13m,...
                 tAlter_palbo750nM_ICI750nMAZD250nM_13m,...
                 xAlter_palbo750nM_ICI750nMAZD250nM_13m,...
                 args.ind_containcdk6,...
                 args);
if ~isnan(mse_use);cost = mse_error;return;end
%% cost value of cell number
% (1)E2(10nM)
mse_E2_c = child_mse(args.timepoint_pro,...
                     data.E210nM_pro,...
                     simE2(args.ind_cellnum,:),...
                     tE2,...
                     args);
data = rmfield(data,'E210nM_pro');

% (4)E2(10nM)+ICI(500nM)
mse_ICI500nM_c = child_mse(args.timepoint_pro,...
                           data.E210nM_ICI500nM_pro,...
                           simICI500nM(args.ind_cellnum,:),...
                           tICI500nM,...
                           args);
data = rmfield(data,'E210nM_ICI500nM_pro');
clear simICI500nM tICI500nM
% (5)E2(100nM)+palbo(250nM)
mse_palbo250nM_c = child_mse(args.timepoint_pro,...
                             data.E210nM_palbo250nM_pro,...
                             simpalbo250nM(args.ind_cellnum,:),...
                             tpalbo250nM,...
                             args);
data = rmfield(data,'E210nM_palbo250nM_pro');
clear simpalbo250nM tpalbo250nM
% (6)E2(100nM)+palbo(500nM)
mse_palbo500nM_c = child_mse(args.timepoint_pro,...
                             data.E210nM_palbo500nM_pro,...
                             simpalbo500nM(args.ind_cellnum,:),...
                             tpalbo500nM,...
                             args);
data = rmfield(data,'E210nM_palbo500nM_pro');
clear simpalbo500nM tsimpalbo500nM
% (7)E2(10nM)+palbo(1uM)
mse_palbo1uM_c = child_mse(args.timepoint_pro,...
                           data.E210nM_palbo1uM_pro,...
                           simpalbo1uM(args.ind_cellnum,:),...
                           tpalbo1uM,...
                           args);
data = rmfield(data,'E210nM_palbo1uM_pro');
clear simpalbo1uM tsimpalbo1uM

% (13) 12 months Mono Alter
% E2(10nM)+palbo(750nM) mono
ind = [2,3,4,5,6,7,13];
% ind = [2,3,4,5,6,7,9,11,12,13];
time_mono_palbo_13m = data.Long12month.time(ind);
data_mono_palbo_13m.mean = data.Long12month.palbo750nM_Mono.mean(ind);
data_mono_palbo_13m.std = data.Long12month.palbo750nM_Mono.std(ind);
[mse_mono_palbo_m12_c,~,val_mono_palbo_m12_c] =...
                               child_mse(time_mono_palbo_13m,...
                               data_mono_palbo_13m,...
                               simpalbo750nM_13m(args.ind_cellnum,:),...
                               tpalbo750nM_13m,...
                               args);
mono_palbo_m12_c = val_mono_palbo_m12_c(end);
clear simpalbo750nM_13m tpalbo750nM_13m

% E2(10nM)+ICI(750nM) mono
ind = [2,6,8,13];
% ind = [2,5,7,8,9,10,11,12,13];
time_mono_ICI_13m = data.Long12month.time(ind);
data_mono_ICI_13m.mean = data.Long12month.ICI750nM_Mono.mean(ind);
data_mono_ICI_13m.std = data.Long12month.ICI750nM_Mono.std(ind);
[mse_mono_ICI_m12_c,~,val_mono_ICI_m12_c] =...
                               child_mse(time_mono_ICI_13m,...
                                         data_mono_ICI_13m,...
                                         simICI750nM_13m(args.ind_cellnum,:),...
                                         tICI750nM_13m,...
                                         args);
mono_ICI_m12_c = val_mono_ICI_m12_c(end);
clear simICI750nM_13m tICI750nM_13m

% E2(10nM)+AZD(250nM) mono
time_AZD250nM = [0,28];
data_AZD250nM.mean = data.E210nM_AZD250nM_pro.mean;
data_AZD250nM.std = data.E210nM_AZD250nM_pro.std;
[mse_mono_AZD250nM_m1_c,~,~] = child_mse(time_AZD250nM,...
                                         data_AZD250nM,...
                                         simAZD250nM_13m(args.ind_cellnum,:),...
                                         tAZD250nM_13m,...
                                         args);
clear simAZD250nM_13m tAZD250nM_13m

% E2(10nM)AZD(250)+ICI(750nM) mono
ind = 2;
time_mono_AZD250nMICI750nM_13m = data.Long12month.time(ind);
data_mono_AZD250nMICI750nM_13m.mean = data.Long12month.AZD250nMICI750nM_Mono.mean(ind);
data_mono_AZD250nMICI750nM_13m.std = data.Long12month.AZD250nMICI750nM_Mono.std(ind);
[mse_mono_AZD250nMICI750nM_m12_c,~,val_mono_AZD_ICI_m12] =...
                               child_mse(time_mono_AZD250nMICI750nM_13m,...
                                         data_mono_AZD250nMICI750nM_13m,...
                                         simICI750nMAZD250nM_13m(args.ind_cellnum,:),...
                                         tICI750nMAZD250nM_13m,...
                                         args);
clear simICI750nMAZD250nM_13m tICI750nMAZD250nM_13m

% Alternating: E2(10nM)+palbo(750nM) -> E2(10nM)+ICI(750nM)
ind = [5,7,8,9,10,11,12,13];
% ind = [3,4,5,6,7,8,9,10,11,12,13];
time_alter_palbo_ICI_13m = data.Long12month.time(ind);
data_alter_palbo_ICI_13m.mean =  data.Long12month.Alter_palbo750nM_ICI750nM.mean(ind);
data_alter_palbo_ICI_13m.std =  data.Long12month.Alter_palbo750nM_ICI750nM.std(ind);
[mse_alter_palbo_ICI_m12_c,~,val_alter_palbo_ICI_m12] =...
    child_mse(time_alter_palbo_ICI_13m,...
              data_alter_palbo_ICI_13m,...
              simAlter_palbo750nM_ICI750nM_13m(args.ind_cellnum,:),...
              tAlter_palbo750nM_ICI750nM_13m,...
              args);
clear simAlter_palbo750nM_ICI750nM_13m tAlter_palbo750nM_ICI750nM_13m

% Alternating: E2(10nM)+palbo(750nM) -> E2(10nM)+ICI(750nM)+AZD(250nM)
% mse_alter_palbo_ICIAZD_m12_c =...
%     child_mse(data.Long12month.time,...
%               data.Long12month.Alter_palbo750nM_ICI750nMAZD250nM,...
%               simAlter_palbo750nM_ICI750nMAZD250nM_13m(args.ind_cellnum,:),...
%                tAlter_palbo750nM_ICI750nMAZD250nM_13m,...
%                args);
max_alter_palbo750nM_ICI750nMAZD250nM_13m =...
    max(simAlter_palbo750nM_ICI750nMAZD250nM_13m(args.ind_cellnum,:));

c = ismember(tAlter_palbo750nM_ICI750nMAZD250nM_13m, (1:2:12)*672);
max_palbo_in_alter_palbo750nM_ICI750nMAZD250nM_13m =...
    max(simAlter_palbo750nM_ICI750nMAZD250nM_13m(args.ind_cellnum,c));

clear simAlter_palbo750nM_ICI750nMAZD250nM_13m tAlter_palbo750nM_ICI750nMAZD250nM_13m

% (20) Rep1-3 Control Proliferation 11day
% mse_E2_day11_c = child_mse(11,...
%                            data.E210nM_day11_pro,...
%                            simE2(args.ind_cellnum,:),...
%                            tE2, ...
%                            args);

% synergy
mse_synergy_ICI200nM  = (cellnum_ICI200nM_d17 - data.Synergy_ICI200nM_17day_pro.mean)^2/...
    data.Synergy_ICI200nM_17day_pro.std^2;
mse_synergy_palbo50nM  = (cellnum_ICI200nM_palbo50nM_d17 - data.Synergy_palbo50nM_17day_pro.mean)^2/...
    data.Synergy_palbo50nM_17day_pro.std^2;
mse_synergy_palbo100nM  = (cellnum_ICI200nM_palbo100nM_d17 - data.Synergy_palbo100nM_17day_pro.mean)^2/...
    data.Synergy_palbo50nM_17day_pro.std^2;
mse_synergy_palbo300nM  = (cellnum_ICI200nM_palbo300nM_d17 - data.Synergy_palbo300nM_17day_pro.mean)^2/...
    data.Synergy_palbo50nM_17day_pro.std^2;
%% 
% (1) E2(10nM) at day11 must higher than threshold_E2_day11
[pos,mse_use] = child_pos(11,tE2/24,args.mse_error);
if ~isnan(mse_use);cost = mse_error;return;end
threshold_E2_day11 = 104;
hillfun_power = 100;
sim_cellnumd11 = simE2(args.ind_cellnum,pos);
penalty_E2_day11 = child_must_higher(sim_cellnumd11,threshold_E2_day11,hillfun_power);

% (2) cyclinE1 E2(10nM)+palbo(750nM) 12m
threshold_cyclinE1ratio_palbo_m12_lowerbound = 1.6;
hillfun_power = 100;
penalty_cyclinE1ratio_palbo_m12_lowerbound =...
    child_must_higher(val_cyclinE1ratio_palbo_m12,...
                      threshold_cyclinE1ratio_palbo_m12_lowerbound,...
                      hillfun_power);

threshold_cyclinE1ratio_palbo_m12_upperbound = 2.3;
hillfun_power = 100;
penalty_cyclinE1ratio_palbo_m12_upperbound =...
    child_must_lower(val_cyclinE1ratio_palbo_m12,...
                     threshold_cyclinE1ratio_palbo_m12_upperbound,...
                     hillfun_power);

% (3) cyclinE Alternating: E2(10nM)+palbo(750nM) -> E2(10nM)+ICI(750nM)+AZD(250nM) 12m
threshold_cyclinE1ratio_alter_palbo_ICIAZD_m12_upperbound = 0.7;
hillfun_power = 100;
penalty_cyclinEratio_alter_palbo_ICIAZD_m12_lowerbound =...
    child_must_lower(val_cyclinE1ratio_alter_palbo_ICIAZD_m12,...
                     threshold_cyclinE1ratio_alter_palbo_ICIAZD_m12_upperbound,...
                     hillfun_power);

% (4) cdk6 E2(10nM)+ICI(750nM) 12m
threshold_Cdk6ratio_ICI_m12_lowerbound = 2.5;
hillfun_power = 100;
penalty_Cdk6ratio_ICI_m12_lowerbound =...
    child_must_higher(val_Cdk6ratio_ICI_m12,...
                      threshold_Cdk6ratio_ICI_m12_lowerbound,...
                      hillfun_power);

threshold_Cdk6ratio_ICI_m12_upperbound = 5;
hillfun_power = 100;
penalty_Cdk6ratio_ICI_m12_uppperbound =...
    child_must_lower(val_Cdk6ratio_ICI_m12,...
                     threshold_Cdk6ratio_ICI_m12_upperbound,...
                     hillfun_power);
    
% (5) Cdk6 Alternating: E2(10nM)+palbo(750nM) -> E2(10nM)+ICI(750nM)+AZD(250nM) 12m
threshold_Cdk6ratio_alter_palbo_ICIAZD_m12_lowerbound = 1.8;
hillfun_power = 100;
penalty_Cdk6ratio_alter_palbo_ICIAZD_m12_lowerbound =...
    child_must_higher(val_Cdk6ratio_alter_palbo_ICIAZD_m12,...
                      threshold_Cdk6ratio_alter_palbo_ICIAZD_m12_lowerbound,...
                      hillfun_power);

threshold_Cdk6ratio_alter_palbo_ICIAZD_m12_upperbound = 3;
hillfun_power = 100;
penalty_Cdk6ratio_alter_palbo_ICIAZD_m12_upperbound =...
    child_must_lower(val_Cdk6ratio_alter_palbo_ICIAZD_m12,...
                     threshold_Cdk6ratio_alter_palbo_ICIAZD_m12_upperbound,...
                     hillfun_power);

% (6) Cellnum E2(10nM+palbo(750nM) mono 12m
threshold_cellnum_palbo_m12_lowerbound = 130;
hillfun_power = 100;
penalty_cellnum_palbo_m12_lowerbound =...
    child_must_higher(mono_palbo_m12_c,...
                      threshold_cellnum_palbo_m12_lowerbound,...
                      hillfun_power);

% (7) Cellnum E2(10nM)+ICI(750nM) mono 12m
threshold_cellnum_ICI_m12_lowerbound = 52;
hillfun_power = 100;
penalty_cellnum_ICI_m12_lowerbound =...
    child_must_higher(mono_ICI_m12_c,...
                      threshold_cellnum_ICI_m12_lowerbound,...
                      hillfun_power);

% (8) Cellnum E2(10nM)+palbo(750nM) -> E2(10nM)+ICI(750nM)+AZD(250nM) 12m
threshold_cellnum_alter_palbo_ICIAZD_m12_upperbound = 4.5;
hillfun_power = 100;
penalty_cellnum_alter_palbo_ICIAZD_m12_upperbound = ...
    child_must_lower(max_alter_palbo750nM_ICI750nMAZD250nM_13m,...
                     threshold_cellnum_alter_palbo_ICIAZD_m12_upperbound,...
                     hillfun_power);

% (9) Cellnum E2(10nM)+palbo(750nM) -> E2(10nM)+ICI(750nM)+AZD(250nM) 12m
threshold_cellnum_alter_palbo_ICIAZD_m12_upperbound_palboarm = 3.4;
hillfun_power = 100;
penalty_cellnum_alter_palbo_ICIAZD_m12__palboarm_upperbound = ...
    child_must_lower(max_palbo_in_alter_palbo750nM_ICI750nMAZD250nM_13m,...
                     threshold_cellnum_alter_palbo_ICIAZD_m12_upperbound_palboarm,...
                     hillfun_power);

% (10) Cellnum E2(10nM)+palbo(750nM) -> E2(10nM)+ICI(750nM)+AZD(250nM) 12m
threshold_cellnum_ICIAZD_m1_lowerbound = 2.5;
hillfun_power = 100;
penalty_cellnum_ICIAZD_m1_lowerbound =...
    child_must_higher(val_mono_AZD_ICI_m12,...
                      threshold_cellnum_ICIAZD_m1_lowerbound,...
                      hillfun_power);

penalty = penalty_E2_day11 +...
          penalty_cyclinE1ratio_palbo_m12_upperbound +...
          penalty_Cdk6ratio_ICI_m12_uppperbound +...
          penalty_cellnum_alter_palbo_ICIAZD_m12_upperbound +...
          penalty_cellnum_palbo_m12_lowerbound +...
          penalty_cellnum_ICI_m12_lowerbound +...
          penalty_Cdk6ratio_alter_palbo_ICIAZD_m12_lowerbound +...
          penalty_cyclinEratio_alter_palbo_ICIAZD_m12_lowerbound +...
          penalty_cellnum_alter_palbo_ICIAZD_m12__palboarm_upperbound +...
          penalty_cellnum_ICIAZD_m1_lowerbound;
          % penalty_Cdk6ratio_alter_palbo_ICIAZD_m12_upperbound +...
          % penalty_cdk6ratio_palbo_m12_upperbound +...
          % penalty_Cdk6ratio_ICI_m12_lowerbound +...
          % penalty_cyclinE1ratio_palbo_m12_lowerbound;
%%
mse_protein = cyclinE1ratio_palbomono_w1 +...
              cyclinE1ratio_palbomono_w2 +...
              cyclinE1ratio_palbomono_m12 +...
              cyclinE1ratio_alter_m12 +...
              cdk6ratio_ICImono_w1 +...
              cdk6ratio_ICImono_w2 +...
              cdk6ratio_ICImono_m12 +...
              cdk6ratio_alter_m12;

mse_cellnum = mse_E2_c +...
              mse_ICI500nM_c +...
              mse_palbo500nM_c +...
              mse_palbo1uM_c;
              % mse_palbo250nM_c +...
              % mse_E2_day11_c;
              % mse_ICI100nM_c +...

mse_cellnum_12m = mse_mono_palbo_m12_c +...
                  mse_mono_ICI_m12_c +...
                  mse_alter_palbo_ICI_m12_c +...
                  mse_mono_AZD250nMICI750nM_m12_c;
                  % mse_alter_palbo_ICIAZD_m12_c +...

synergy = mse_synergy_ICI200nM +...
          mse_synergy_palbo50nM +...
          mse_synergy_palbo100nM +...
          mse_synergy_palbo300nM;

% mse_cellnum_12m < 5e3
threshold_mse_cellnum_12m_upperbound = 2.1e3;
hillfun_power = 100;
penalty_mse_cellnum_12m_upperbound =...
child_must_lower(mse_cellnum_12m,threshold_mse_cellnum_12m_upperbound,hillfun_power);
penalty = penalty + penalty_mse_cellnum_12m_upperbound;

cost = penalty +...
       mse_mono_AZD250nM_m1_c +...
       mse_cellnum_12m +...
       synergy +...
       mse_cellnum +...
       mse_protein;
end

function [pos,mse_use] = child_pos(tdata,tsim,mse_error)
pos = zeros(numel(tdata),1);
for i = 1 : numel(tdata)
    pos(i) = find(tsim == tdata(i),1,'first');
    if isempty(pos(i))
        mse_use = mse_error;
        return;
    end
end
mse_use = nan;
end

function [msetotal,mse_use,val] = child_mse(texp,exp,sim,t,args)
[pos,mse_use] = child_pos(texp,t/24,args.mse_error);
if ~isnan(mse_use) || numel(exp.mean) ~= numel(sim(:,pos))
    msetotal = args.mse_error;
    mse_use = args.mse_error;
    val = -1;
    return;
end
mse = (exp.mean - sim(:,pos)).^2;
val = sim(:,pos);
try
    mse = mse .* (1./exp.sem.^2);
catch
    mse = mse .* (1./exp.std.^2);
end
msetotal = sum(mse,'all','omitnan');
end

function [msetotal,mse_use, x_norm] = child_mse_p2(data,x,t,xref,ind,args)
[pos,mse_use] = child_pos(data.time,t/24,args.mse_error);
if ~isnan(mse_use)
    msetotal = args.mse_error;
    mse_use = args.mse_error;
    return;
end
x_norm = sum(x(pos,ind))/sum(xref(1,ind));
mse = (data.mean - x_norm).^2;
mse = mse .* (1./data.sem.^2);
msetotal = sum(mse,'all',"omitnan");
end


function penalty_out = child_must_higher(sim,threshold,hillfun_power)
penalty_out = 1/(sim/threshold)^hillfun_power;
end

function penalty_out = child_must_lower(sim,threshold,hillfun_power)
penalty_out = 1/(threshold/sim)^hillfun_power;
end